### ISSUE TITLE
store phone number in freeBotTrial collection

### ISSUE THREAD

**Issue by AndrewMagliozzi** [AdmitHub/Admit#175]
That makes our FB conversion tracking easier

**Comment by yourcelf** [comment]
I'd prefer to avoid this if possible, as it makes updating harder.  Is the enough to have the phone number show up on the freetrialstats page?  Or is there a reason why it really needs to be duplicated?

**Comment by AndrewMagliozzi** [comment]
not essential any more.  I just gave out advertisers access to our online system so they can see the data as they like.  It's easier than sending a JSON dump to them.
