### ISSUE TITLE
Bot improvements

### ISSUE THREAD

**Issue by AndrewMagliozzi** [AdmitHub/Admit#187]
## Catch duplicate parent phone numbers

A common problem is students inputing their own phone number when we ask for their parent's number.  

We need to change the copy when we ask for the parent number to something like this: "Could you enter your parent's cell phone number so we can text them occasional updates about your progress?"

If a student inputs the same number as the one we are already texting, let's catch the error and return: "The number you entered looks like your phone number.  Could you enter your parent's cell phone number?  Or type #skip to move on to the next question."

## More improvements to make
 - [x] only ask for parent emails if the student skips the phone number field (we only need one form of contact)
 - [x] instead of home city and state, let's ask for home zip code
 - [x] let's change the copy on oneQuestion
 - [x] if a student says we can post their oneQuestion to the forum, let's follow up and ask them for a username to use as their signature

**Comment by yourcelf** [comment]
Remember, our current bot logic handler doesn't support custom skip logic based on other responses.  We can implement something like this, but it's more involved than just changing the script -- it will require some careful reworking of some of the forward/backward question flow logic.

**Comment by AndrewMagliozzi** [comment]
One simplification we can make is to omit the #back feature as none of our 246 users has ever gone back to a previous question via SMS.

**Comment by yourcelf** [comment]
OK, we now have custom skip logic, pausing, and custom actions.  "#back" support is removed.  "oneQuestion" is removed from the latest script, so those two points are now moot.

Parent phone copy is updated; but validating that it isn't the same as the user's phone number is another tricky point with our current implementation -- the SimpleSchema validator doesn't have access to the user object which contains the phone number. We could look it up based on the userId set on the model, but then we have sync/async issues if it's run on the client.

If it's alright I'd like to defer the validation that the phone # isn't the user's and see if the copy changes are adequate.

**Comment by AndrewMagliozzi** [comment]
Hey Charlie, I'm game to punt on the phone number validation.  We'll see
what happens.
