### ISSUE TITLE
Fire Facebook Conversions on Web-based bot

### ISSUE THREAD

**Issue by AndrewMagliozzi** [AdmitHub/Admit#193]
See how to do this here: http://stackoverflow.com/questions/19261604/firing-the-facebook-conversion-pixel

**Comment by AndrewMagliozzi** [comment]
looks like this is done, but I'll await confirmation from @yourcelf

**Comment by yourcelf** [comment]
Done. https://github.com/AdmitHub/admithub-telescope-theme/commit/c39a06be4ba701bac810f283794ac562e5de710b

**Comment by AndrewMagliozzi** [comment]
Great. I got some new specifics from our marketing consultants. I made a new ticket to tweak these events next week.
