### ISSUE TITLE
Categories don't load on Firefox

### ISSUE THREAD

**Issue by daulerio** [AdmitHub/Admit#199]

**Comment by yourcelf** [comment]
Need more info -- they're loading for me.  Can you send me a link to a page, or steps to reproduce?

**Comment by daulerio** [comment]
Hey Charlie,

It seems to be working for me fine now.  Not sure what happened...

— 
Kirk Daulerio
Co-Founder | AdmitHub
Harvard Innovation Lab
125 Western Ave.
Boston, MA  02134

AdmitHub.com <http://admithub.com/>
facebook <https://www.facebook.com/AdmitHub> | twitter <https://twitter.com/AdmitHub> | LinkedIn <http://www.linkedin.com/pub/kirk-daulerio/8/387/407/>
P: 617-982-3662 <tel:617-982-3662>

**Comment by yourcelf** [comment]
Gonna close this and track category opening issues with #200, as it affects more than just Firefox if it happens.
