### ISSUE TITLE
Response on forum is getting cut off

### ISSUE THREAD

**Issue by daulerio** [AdmitHub/Admit#204]
full answer isn't visible

https://college.admithub.com/posts/Mjani5KAz8xF8ZHrC/p/should-i-do-a-startup-or-go-to-college-

**Comment by daulerio** [comment]
another exampe...

https://college.admithub.com/posts/AZwpLXtzLrCxyyTFc/p/how-do-you-think-the-new-sat-will-affect-the-college-admissions-process-

**Comment by daulerio** [comment]
looks like every response is getting cut off after the first paragraph break:

https://college.admithub.com/posts/FywPSsq8abNC7oCgq/p/two-interviews-for-one-university-

**Comment by yourcelf** [comment]
fix is building on staging, will push to production after verifying

**Comment by yourcelf** [comment]
Fix deployed to production.

**Comment by AndrewMagliozzi** [comment]
Thanks!
